language: python

notifications:
  email:
    - sdk_dev@couchbase.com

branches:
  except:
    - failing-tests

env:
  - CB_URL="http://packages.couchbase.com/releases/1.8.0/couchbase-server-community_x86_1.8.0.deb" CB_DEB="couchbase-server-community_x86_1.8.0.deb" CB_VER="1.8.0"
  - CB_URL="http://packages.couchbase.com/releases/2.0.0-developer-preview-4/couchbase-server-community_x86_2.0.0-dev-preview-4.deb" CB_DEB="couchbase-server-community_x86_2.0.0-dev-preview-4.deb" CB_VER="2.0.0"

python:
  - "2.6"
  - "2.7"

before_install:
  - wget -q $CB_URL
  - sudo dpkg -i $CB_DEB
  - sudo chmod a+x cluster_connect
  - ./cluster_connect -n 1
  - cp test.ini.template test.ini

install:
  - pip install nose-testconfig coverage

script: nosetests --tc-file=test.ini --with-coverage --cover-package=couchbase --cover-html -A "(cbv <= \"${CB_VER}\")"
